[package]
name = "cmps"
version = "0.1.0"
authors = ["Björn Daase <bjoern@daase.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.33.3", features = ["yaml"]}
dirs = "3.0.1"
log = "0.4.11"
